update

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -38,6 +38,12 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v4
 
+    - name: Extract branch name
+      shell: bash
+      run: |
+         echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | tr '/' '-' >> $GITHUB_OUTPUT
+      id: extract_branch
+
     # Install the latest version of the Terraform CLI
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
@@ -53,12 +59,7 @@ jobs:
         jo -p terraform=$(jo backend=$(jo azurerm={})) \
                 resource=$(jo azurerm_resource_group=$(jo observe_resource_group=$(jo name="rg-branchname"))) > override.tf.json
         printenv | grep GITHUB
-
-    - name: Extract branch name
-      shell: bash
-      run:  echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" | tr '/' '-' >> $GITHUB_OUTPUT
-      id: extract_branch
-
+   
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       id: init
@@ -68,4 +69,37 @@ jobs:
         -backend-config="storage_account_name=citeststfazurecollection" \
         -backend-config="container_name=tfstate" \
         -backend-config="key=${{ steps.extract_branch.outputs.branch }}/.tfstate" 
+
+    # Checks that all Terraform configuration files adhere to a canonical format
+    # Will fail the build if not
+    - name: Terraform Format
+      run: terraform fmt -check
+
+    - name: Terraform Validate
+      id: validate
+      run: terraform validate -no-color
+
+    # Generates an execution plan for Terraform
+    # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+    - name: Terraform Plan
+      id: tf-plan
+      run: |
+        export exitcode=0
+        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT        
+        if [ $exitcode -eq 1 ]; then
+          echo Terraform Plan Failed!
+          exit 1
+        else 
+          exit 0
+        fi
+
+    - name: Error in Terraform 
+      if: steps.tf-plan.outputs.exitcode == 1
+      run: exit 1
+
+    # # Terraform Apply if no errors in plan 
+    # - name: Terraform Apply     
+    #   run: terraform apply -auto-approve tfplan
+
 
